### ISSUE TITLE
Tracking upstream bugs

### ISSUE THREAD

**Issue by craigbarnes** [craigbarnes/lua-gumbo#59]
The upstream gumbo library hasn't seen a new commit in nearly 18 months and seems like it will probably go unmaintained indefinitely. There are a bunch of unresolved bugs on the [issue tracker](https://github.com/google/gumbo-parser/issues), a few of which have security implications.

Because of this, lua-gumbo now keeps a fork of the libgumbo code in the [`lib/`](https://github.com/craigbarnes/lua-gumbo/tree/master/lib) directory and no longer links with the upstream distributed `libgumbo.so` for any new builds.

This issue is to track the bugs reported upstream and their status with regards to the forked code in `lib/`.

* [x] google/gumbo-parser#388 "Out of memory usually crashes" -- lua-gumbo has used a `malloc` wrapper to prevent segfaults on OOM since before the `0.3` release.
* [x] google/gumbo-parser#381 "Possible XSS in serializers that use `gumbo_tag_from_original_text`" -- lua-gumbo not affected.
* [x]  google/gumbo-parser#391 "Quadratic time and memory use with many unclosed tags" -- lua-gumbo disables the code that causes this buggy behaviour and thus isn't affected.
* [x] google/gumbo-parser#393 "Quadratic time and memory use on very deep trees" -- fixed by limiting the maximum tree depth in the parser (176553e)
* [x] google/gumbo-parser#387 "`destroy_node()` is recursive" -- fixed by commit df15262924a
* [x] google/gumbo-parser#386 "Don't use `<ctype.h>` functions" -- equivalent patch already applied to the fork in `lib/`
* [x] google/gumbo-parser#350 "[Can]not detect the end of the tag `<form>`" -- fixed in `lib/`, although the Lua API was never affected

**Comment by craigbarnes** [comment]
The best fix for google/gumbo-parser#393 would be a tree depth limit in the parser loop. Probably 512 to match WebKit.

I plan to fix google/gumbo-parser#387 by switching to an arena allocator, similar to the google/gumbo-parser#309 PR, but without the bugs.

**Comment by craigbarnes** [comment]
These are all fixed now.
